<?php


namespace app\index\controller;

use think\facade\View;

class Helps extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $action = request()->action();

        switch ($action) {
            case 'about':
                $title = '关于我们-';
                break;
            case 'copyright':
                $title = '版权声明-';
                break;
            case 'contact':
                $title = '联系我们-';
                break;
            case 'points':
                $title = '获取积分-';
                break;
        }
        View::assign('seo_title', $title.config('app.web_site_title'));
        View::assign('action', request()->action());
    }

    public function about()
    {
        return View::fetch();
    }

    public function contact()
    {
        return View::fetch();
    }

    public function copyright()
    {
        return View::fetch();
    }

    public function points()
    {
        return View::fetch();
    }
}
