<?php
declare (strict_types = 1);

namespace app\index\controller;


use think\facade\View;

class Tools extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $_channel = request()->controller(true);

        View::assign('_channel',$_channel);
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        return View::fetch();
    }

    public function fenci(){
        $seo = [
            'seo_title' => 'PHP中文分词、phpanalysis分词-'.config('api.web_site_title')
        ];

        View::assign($seo);
        return View::fetch();
    }

    public function seoai(){
        $seo = [
            'seo_title' => '智能AI文章伪原创-'.config('api.web_site_title')
        ];

        View::assign($seo);
        return View::fetch();
    }

    public function pinyin(){
        $seo = [
            'seo_title' => '智能AI文章伪原创-'.config('api.web_site_title')
        ];

        View::assign($seo);
        return View::fetch();
    }

    public function md5(){
        $seo = [
            'seo_title' => 'MD5在线加密工具-'.config('api.web_site_title')
        ];

        View::assign($seo);
        return View::fetch();
    }
}
