<?php

namespace app\admin\controller;


use app\model\AgentConfigs;
use app\model\Roles;
use app\model\Users;
use think\facade\View;

class User extends Base
{
    public $roles;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->roles = Roles::where('status', 1)->select()->toArray();

        View::assign('roles', $this->roles);
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
        $field = input('_order', 'id');
        $_by   = input('_by', 'desc');
        // 查询
        $map = $this->getMap();
        if ($map)
            $list = Users::where($map)->order($field, $_by)->paginate(20, false, ['query' => input('get.')]);
        else
            $list = Users::order($field, $_by)->paginate(20, false, ['query' => input('get.')]);

        View::assign(['list' => $list, 'field' => $field]);
        return View::fetch();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
        if (request()->isAjax()) {
            $this->save();
        }
        return View::fetch('info');
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int $id
     * @return \think\Response
     */
    public function edit()
    {
        $info = Users::find(input('id'))->toArray();
        if (request()->isAjax()) {
            $this->save();
        }
        View::assign($info);
        return View::fetch('info');
    }

    public function level()
    {
        $id = input('id');
        if (request()->isAjax()) {
            $data  = input('post.');
            $level = $data['level'];
            switch (intval($level)) {
                case -1:
                    $over_time = 0;
                    $vip_name  = '普通用户';
                    break;
                case 0:
                    $over_time = strtotime('+1 day');
                    $vip_name  = '体验会员';
                    break;
                case 1:
                    $over_time = strtotime('+1 month');
                    $vip_name  = '体验会员';
                    break;
                case 2:
                    $over_time = strtotime('+3 month');
                    $vip_name  = '体验会员';
                    break;
                case 3:
                    $over_time = strtotime('+6 month');
                    $vip_name  = '体验会员';
                    break;
                case 4:
                    $over_time = strtotime('+1 year');
                    $vip_name  = '体验会员';
                    break;
            }

            $user = Users::field('over_time')->find($data['id']);
            $time = $user['over_time'] - time();
            if ($time > 0) {
                $over_time = $over_time + $time;
            }
            $item = [
                'over_time' => $over_time, 'vip_name' => $vip_name, 'is_recharge' => 1, 'id' => $data['id'],
                'is_vip'    => 1
            ];
            $res  = Users::update($item);
            $this->success('设置成功~');
        }
        $levels = AgentConfigs::getRechargeConf();

        View::assign('id', $id);
        View::assign('levels', $levels);
        return View::fetch();
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request $request
     * @return \think\Response
     */
    public function save()
    {
        //
        $data           = input('post.');
        $data['status'] = $data['status'] ? 1 : 0;

        if ($data) {
            $time                = time();
            $data['update_time'] = $time;
            if ($data['id']) {
                if ($data['password']) {
                    $data['password'] = md5($data['code'] . $data['password']);
                }else{
                    unset($data['password']);
                }
                $res = Users::update($data);
            } else {
                $data['create_time'] = $time;
                $data['code']        = getAssignStr(5);
                if ($data['password']) {
                    $data['password'] = md5($data['code'] . $data['password']);
                }else{
                    unset($data['password']);
                }
                $res = Users::insert($data);
            }

            $res ? $this->success('操作成功~') : $this->error('操作失败~');
        }
    }
}
